### PR TITLE
GE Muzzle flash addition

### PR DESCRIPTION
**Pull request by Nyxem64**
This was how I (HackBond) did the GE-style muzzle flash that was requested in this issue https://github.com/fgsfdsfgs/perfect_dark/issues/259

Feel free to change it however is needed.

### CODE REVIEW

**Comment by PeeMoldy** [comment]
I'm excited! Can't wait til this gets merged.

**Comment by Bobbar** [comment]
This works great.  I didn't even realize how broken it was until now! :smile:

**Comment by PeeMoldy** [comment]
> This works great. I didn't even realize how broken it was until now! 😄

Did you add it to your mod version of the PC Port that has the infinite ammo for Psychosis Gun and K7 Threat Detector Muzzle Flash fix?

**Comment by MUL1NSK1** [comment]
I don't see any muzzle flash on semi-automatic weapons like the Falcon 2 now. (steam deck, 60hz/fps)

**Comment by fgsfdsfgs** [comment]
Download the new version.

**Comment by MUL1NSK1** [comment]
Uhh that looks/feels great. thx :)

**Comment by MUL1NSK1** [comment]
Hm. Some Weapons just stop showing muzzle flash mid-game. Tried it multiple times with new version. 

Edit: Try K7 Avenger in Combat Simulator

**Comment by Bobbar** [comment]
K7 won't have muzzle flash while in threat detect mode.

I've been playing a lot with these changes and haven't noticed any issues. I'll have to take another closer look.

**Comment by MUL1NSK1** [comment]
Oh, was that always the case? I never noticed. Sorry for the confusion.

**Comment by PeeMoldy** [comment]
> Oh, was that always the case? I never noticed. Sorry for the confusion.

Yeah man that's a vanilla n64 bug. But those new GE64 muzzle flashes are sexy and this is the best build yet!

**Pull request merged**
