### PR TITLE
Improve windows build instructions

### PR DESCRIPTION
**Pull request by TwitchBronBron**
Adds more details to the windows build instructions.

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
I'm not overly familiar with msys2 or building c/c++ projects, so I ran into a few issues that took me a while to get up and running. I figure it makes sense to update the instructions to fill in some of those gaps so the next noob like me doesn't have to struggle through them as well. :)

**Comment by fgsfdsfgs** [comment]
Huh, I don't have to do any of this. Have you tried installing `mingw-w64-i686-pkg-config`? Are you building in the MINGW32 environment? What are the issues you're having if you just follow the current instructions?

**Comment by TwitchBronBron** [comment]
Oh!. I was using the msys2 executable. I didn't even realize there was a separate mingw32 executable. Now that I read back through the readme, I do see it specifically says "Open the MINGW32 prompt.". 
image

I just uninstalled everything, and started from scratch and followed the instructions using `mingw32.exe` instead, and it all works without issue. lol

**Comment by TwitchBronBron** [comment]
I updated the PR to specifically call out to _not_ use the msys2.exe prompt, and removed the stuff you don't actually need to do when you actually follow the instructions. 🤦‍♂️

**Pull request merged**
