### PR TITLE
Implement some dedicated buttons for mouse+kb / gamepad

### PR DESCRIPTION
**Pull request by cylonicboom**
Implements dedicated buttons for:

- alt switching: F / RB. Hold F and release to switch modes. Hold F, press the trigger to temporarily use the alt mode, and release to switch back. Both chords will trigger crouch toggling with the sniper rifle.
- radial menu: G / LB
- reloading: R / X

### CODE REVIEW

**Comment by 8sm32K4D1K5f3E** [comment]
Love this, was hoping exactly this kind change would be made, small change but such a big improvement.

I noticed the swap function does have a small bug with its display with weapons that have their function work while swap is held, if the button's held, the function doesn't show it's swapped at all, but it still works. If you merely press the button, the text does update, then stay on the swapped text, despite the weapon itself returning to its primary fire.

[2023-08-18 22-56-06.webm](https://github.com/fgsfdsfgs/perfect_dark/assets/97014490/8bbf62af-4ded-4628-bded-43c9b96815cd)

**Comment by cylonicboom** [comment]
Thank you, good catch!

I'll check this. By the way, were you activating alt mode with holding E / B or by holding F / X?

**Comment by 8sm32K4D1K5f3E** [comment]
That occurs when using the dedicated F key, when holding E the display functions as expected.

**Comment by cylonicboom** [comment]
> Love this, was hoping exactly this kind change would be made, small change but such a big improvement.
> 
> I noticed the swap function does have a small bug with its display with weapons that have their function work while swap is held, if the button's held, the function doesn't show it's swapped at all, but it still works. If you merely press the button, the text does update, then stay on the swapped text, despite the weapon itself returning to its primary fire.
> 2023-08-18.22-56-06.webm

Okay, see what you mean. TLDR it's a feature for the dedicated button because I discovered during testing it felt better.

long answer: An immediate mode switch felt best, but my muscle memory expected "one-off alt-mode behavior" when the dedicated button was held. Switching to the one-off mode when Z trigger is pressed but hard-switching it if the F button was released without pressing Z felt best during my testing.

**Comment by cylonicboom** [comment]
>>  If you merely press the button, the text does update, then stay on the swapped text, despite the weapon itself returning to its primary fire.

I need to look at xbla behavior but I think the laptop gun / dragon special cases aren't being handled here. But I agree, it's definitely odd. I should be able to fix it.

**Comment by fgsfdsfgs** [comment]
Should I merge this or wait for the fix?

**Comment by LanHikariDS** [comment]
> I need to look at xbla behavior but I think the laptop gun / dragon special cases aren't being handled here.

XBLA just makes the Dragon/Laptop Gun Alt-modes act like other guns, where it just toggles into the new mode, no holding while firing required.

**Comment by cylonicboom** [comment]
> > I need to look at xbla behavior but I think the laptop gun / dragon special cases aren't being handled here.
> 
> XBLA just makes the Dragon/Laptop Gun Alt-modes act like other guns, where it just toggles into the new mode, no holding while firing required.

Thank you for saving me the trouble of hooking up my xbox!

**Comment by cylonicboom** [comment]
> Should I merge this or wait for the fix?

I'll fix it. The laptop gun / dragon should switch but they're switching back on the next tick w/o updating the UI...which is neither vanilla or xbla behavior and just kind of feels weird.

**Comment by cylonicboom** [comment]
I fixed the issue that @8sm32K4D1K5f3E  reported but I found another issue: the sniper rifle doesn't respect F while aiming. And this, tbh is because this mod was originally for the mouse injector compatibility branch and the crouching was overridden by the memory injection shenanigans. The correct fix for that is to implement squatting and half-crouch buttons in the rom. I'll disable F for sniper rifle, as that's afaicr xbla behavior and what you'd expect if you had functioning crouch / half-crouch buttons.

**Comment by cylonicboom** [comment]
> I fixed the issue that @8sm32K4D1K5f3E reported but I found another issue: the sniper rifle doesn't respect F while aiming. And this, tbh is because this mod was originally for the mouse injector compatibility branch and the crouching was overridden by the memory injection shenanigans. The correct fix for that is to implement squatting and half-crouch buttons in the rom. I'll disable F for sniper rifle, as that's afaicr xbla behavior and what you'd expect if you had functioning crouch / half-crouch buttons.

actually no this feels awful I'll try to make it work with F

**Comment by cylonicboom** [comment]
How do we feel about these bindings for the sniper rifle alt fire button?

- F+trigger: half-crouch
- F: full crouch

(or vice versa)

**Comment by LanHikariDS** [comment]
In the case of the XBLA port, the Sniper's alt-fire gets removed entirely, since crouch gets its own bind (LS)

**Comment by cylonicboom** [comment]
> How do we feel about these bindings for the sniper rifle alt fire button?
> 
>     * F+trigger: half-crouch
> 
>     * F: full crouch
> 
> 
> (or vice versa)



> In the case of the XBLA port, the Sniper's alt-fire gets removed entirely, since crouch gets its own bind (LS)

You're right, but people might be using 1 or more n64 controllers and might expect a dedicated alt button to work the n65 way.

**Comment by cylonicboom** [comment]
> How do we feel about these bindings for the sniper rifle alt fire button?
> 
>     * F+trigger: half-crouch
> 
>     * F: full crouch
> 
> 
> (or vice versa)

I have f-to-crouch working, now for f+z-to-halfcrouch

**Comment by cylonicboom** [comment]
@fgsfdsfgs can the different levels of alt-mode support (none, crouch-only, and crouch+halfcrouch) for the sniper rifle switch-able options be in an extended options menu later?

**Comment by LanHikariDS** [comment]
> You're right, but people might be using 1 or more n64 controllers and might expect a dedicated alt button to work the n65 way.

Ah, I assumed these changes only applied when using a keyboard. Alternatively, why not just leave the alt-fire alone and give a dedicated Crouch cycle key (Again like 360)? N64 DOES have a standalone functionality for it as well, the Sniper Alt is just meant to be a more convenient way to trigger it

**Comment by cylonicboom** [comment]
> > You're right, but people might be using 1 or more n64 controllers and might expect a dedicated alt button to work the n65 way.
> 
> Ah, I assumed these changes only applied when using a keyboard. Alternatively, why not just leave the alt-fire alone and give a dedicated Crouch cycle key (Again like 360)? N64 DOES have a standalone functionality for it as well, the Sniper Alt is just meant to be a more convenient way to trigger it

Right now only the keyboard bindings are added, but controller support is just a matter of mapping the inputs

**Comment by cylonicboom** [comment]
> > > You're right, but people might be using 1 or more n64 controllers and might expect a dedicated alt button to work the n65 way.
> > 
> > 
> > Ah, I assumed these changes only applied when using a keyboard. Alternatively, why not just leave the alt-fire alone and give a dedicated Crouch cycle key (Again like 360)? N64 DOES have a standalone functionality for it as well, the Sniper Alt is just meant to be a more convenient way to trigger it
> 
> Right now only the keyboard bindings are added, but controller support is just a matter of mapping the inputs

Because these are patches that I originally wrote for a 1964 compatibility mod. Crouching was handled by the plugin, these patches I had to write b/c the asm hacks needed to be in the decomp project.

Dedicated crouching / uncrouching buttons are coming, I promise! If not me then someone else will write it.

**Comment by fgsfdsfgs** [comment]
> @fgsfdsfgs can the different levels of alt-mode support (none, crouch-only, and crouch+halfcrouch) for the sniper rifle switch-able options be in an extended options menu later?

Eventually probably. Ideally I'd want all enhancements to be switchable, but for some that might be too awkward.

**Comment by Graslu** [comment]
IMO radial menu should be on Q instead of G - closer to WASD and it's what most modern shooters seem to use nowadays (DOOM 2016, Eternal, Quake remasters). Once the dedicated button for crouch and half crouch is added I assume the crouch option for the sniper won't be required. Can't crouch in the original with the FarSight unless you crouched beforehand.

I assume that in the future we'll also have custom bindings so it won't be a big issue. Also native N64 support with Raphnet hopefully for the true 1:1 experience. :P

**Comment by cylonicboom** [comment]
> IMO radial menu should be on Q instead of G - closer to WASD and it's what most modern shooters seem to use nowadays (DOOM 2016, Eternal, Quake remasters). Once the dedicated button for crouch and half crouch is added I assume the crouch option for the sniper won't be required. Can't crouch in the original with the FarSight unless you crouched beforehand.
> 
> I assume that in the future we'll also have custom bindings so it won't be a big issue. Also native N64 support with Raphnet hopefully for the true 1:1 experience. :P

I added new issues b/c resolving @Graslu's issue is out of scope b/c crouch/half-crouch/back-switch buttons are missing.

- https://github.com/fgsfdsfgs/perfect_dark/issues/41
- https://github.com/fgsfdsfgs/perfect_dark/issues/40
- https://github.com/fgsfdsfgs/perfect_dark/issues/42

**Comment by cylonicboom** [comment]
F-Trigger to half-crouch w/ sniper is nontrivial enough to be out of scope for this PR as well as being a purely non-vanilla idea I had in this thread.

I filed issues for the unimplemented features that people here have mentioned. @fgsfdsfgs  I think this is ready to merge.

**Comment by Phnod** [comment]
Could the Radial menu button also be on the Middle Mouse button or Mouse5 (`VK_MOUSE_X2`)? it's a little less awkward to input the directional keys for selecting a weapon when you don't have to hold a key right next to them. For instance trying to select the bottom left option in the radial menu is a little awkward holding down Q, A and S combined.

**Comment by cylonicboom** [comment]
> Could the Radial menu button also be on the Middle Mouse button or Mouse5 (`VK_MOUSE_X2`)? it's a little less awkward to input the directional keys for selecting a weapon when you don't have to hold a key right next to them. For instance trying to select the bottom left option in the radial menu is a little awkward holding down Q, A and S combined.

Yes!

Also mouse movement within the menu can be added in another PR. This PR is just about porting / upstreaming relevant decomp-side 1964 patches.

**Comment by cylonicboom** [comment]
> > Could the Radial menu button also be on the Middle Mouse button or Mouse5 (`VK_MOUSE_X2`)? it's a little less awkward to input the directional keys for selecting a weapon when you don't have to hold a key right next to them. For instance trying to select the bottom left option in the radial menu is a little awkward holding down Q, A and S combined.
> 
> Yes!
> 
> Also mouse movement within the menu can be added in another PR. This PR is just about porting / upstreaming relevant decomp-side 1964 patches.

I added an alternate mapping to middle mouse for the radial menu. Moving Q doesn't make sense until there's a dedicated back-switch button which is out of scope for this PR.

**Pull request merged**
