### PR TITLE
flatpak: introduce hacky flatpak support

### PR DESCRIPTION
**Pull request by D1sc0Inferno**
This is a working configuration to generate the perfect dark PC port flatpak. I mostly made this for myself as I wanted an easy way to play on the SteamDeck and I've tested and beaten the game already using it.

Opening this PR to see if there is any appetite to upstream this, that way it could potentially be rolled out to flathub as well.

If there is, I'm willing to work on the following items to clean this branch up:
- Change file handling logic to allow changing the data directory without needing patch file, potentially use more idiomatic `~/.var/app/<app-id>/config` instead of custom `~/.perfectdark` directory
- Replacing logo with something more free, this one is just cribbed from SteamGridDB (https://www.steamgriddb.com/icon/9007 unsure of license)
- Small makefile changes to support flatpak toolchain a little more gracefully (optional, i'm not convinced it's needed)
- Change this from a PR to it's own repo for introduction to flathub

 Consider all this MIT licensed (with obvious exception of images), so if someone wants to carry this through then be my guest. But as stated I'm willing to do the above.

For those wanting to give it a spin, you can build it with the following command:
`flatpak-builder --install --user build-dir local.d1sc0inferno.fgsfdsfgs.perfectdark.yml`

Or you can grab my precompiled `.flatpak` file here: https://github.com/D1sc0Inferno/perfect_dark/releases/tag/v0.0.1

Because this is a 3rd party file, you will need to install the runtime and runtime extensions:
```
org.freedesktop.Platform//23.08
org.freedesktop.Platform.Compat.i386//23.08
org.freedesktop.Platform.GL32//23.08
```

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
The "store data in $HOME" part definitely should be implemented in the port regardless. I'll try to generalize it a bit.

**Comment by D1sc0Inferno** [comment]
It looks to pull from a Config setting, but I couldn't figure out how that logic exactly works from a quick glance, so maybe it already exists somehow?

The leading `./` on `pd.ini` and `eeprom.bin` was the biggest issue as the logic just ignores the data directory configuration when the file string has a leading period.

**Comment by fgsfdsfgs** [comment]
That was set up that way because I tend to run the game from the `build` folder, but my data files are in the repository root.
Check out the latest commit, I've added support for saving to `~/.local/share/perfectdark`. Data files (ie ROM) can also be loaded from there.
You can override the data file path with the `--datadir` command line argument and the save/config path with the `--savedir` command line parameter.

**Comment by tunbridgep** [comment]
I actually think an AppImage would be about perfect for this. It's the perfect size to work as a portable app.

**Comment by fgsfdsfgs** [comment]
This has been implemented in #502.

**Pull request closed without merging**
