### PR TITLE
64-bit port

### PR DESCRIPTION
**Pull request by rafccq**
Summary of changes:

- Assets conversion to 64-bit: all pointers inside assets structures changed to 8-byte, and all offsets updated accordingly
- GDL commands are now 128-bit wide instead of 64. All GDLs inside assets are converted 
- Memory allocations: adjusted allocation sizes in locations where it's hardcoded and some systems heap sizes
- Every location that stored/cast a pointer using s32/u32 changed to intptr_t/uintptr_t
- Manually added pad to some structures that contain pointers (casting/alignment requirements)

### CODE REVIEW

**Comment by FrostKnight** [comment]
Are these the commits to make 64 bit only possible?

**Comment by rafccq** [comment]
32-bit is still supported. In fact, the release will include both 32 and 64-bit builds.

**Comment by FrostKnight** [comment]
> 32-bit is still supported. In fact, the release will include both 32 and 64-bit builds.

Oh no I meant, do you still need 32 bit libraries to build for the 64 bit version.

**Comment by rafccq** [comment]
no, you just need the 64-bit versions of the same libraries used in the 32-bit build.

**Comment by FrostKnight** [comment]
> no, you just need the 64-bit versions of the same libraries used in the 32-bit build.

Including the multilib ones? If so that is my point. I was wondering when those would no longer be needed

**Comment by rafccq** [comment]
To be honest, I haven't checked if those can be removed, I just added the 64-bit libraries to the x64 build. I can check that later.

**Comment by fgsfdsfgs** [comment]
Will merge this now for ease of work. It is possible something might break for a while until I'm finished going through the changes.

**Pull request merged**
