### PR TITLE
Allow classic weapons to be used in multiplayer

### PR DESCRIPTION
**Pull request by tmyqlfpir**
_As this is a gameplay enhancement, I am not too sure if this PR will be accepted._

This PR adds the classic weapons in the multiplayer menu, and implements some basic defaults for bots to use them appropriately.

### CODE REVIEW

**Comment by tmyqlfpir** [comment]
Ready to be merged.

**Comment by fgsfdsfgs** [comment]
I am a bit wary of the "modifying mpconfig IDs" part. Is there a reason why you had to insert them in the middle of the `MPWEAPON_` list instead of adding them to the end?

**Comment by tmyqlfpir** [comment]
Simply to mirror the same weapon order in-game. I originally had the weapons placed after disabled, but I understand if that might complicate things. I'll revert back to what I had originally then.

**Comment by fgsfdsfgs** [comment]
Okay, and if you do it this way it doesn't have the unselectable shield problem like reported in that one issue?

**Comment by tmyqlfpir** [comment]
[Not anymore.](https://github.com/fgsfdsfgs/perfect_dark/assets/80724828/aa752073-7f9f-4739-9206-b37c6d29aa5a)

**Comment by fgsfdsfgs** [comment]
Alright, was just confirming.

**Comment by tmyqlfpir** [comment]
Thanks!

**Pull request merged**
