### PR TITLE
Add Flatpak build

### PR DESCRIPTION
**Pull request by fpiesche**
The regular Linux builds here cannot be run on e.g. a Steam Deck, which does not have the libraries required to run 32bit executables and installing them is difficult due to how the Linux system on the Deck works. This is likely also the case on other "immutable" Linux distributions such as Bazzite or Fedora Silverblue.

This PR circumvents this problem, and generally makes the Linux distributions easier to use and install, by packaging them in a [Flatpak](https://www.flatpak.org/) package. Flatpak is supported by most modern Linux distributions out of the box and sandboxes applications and their dependencies away from the host system.

The .flatpak package, about 1.5MB in size, will also be automatically attached to the release on builds. You can have a look at my forked repo to see how the workflow and releases look with these changes.

The Flatpak bundle built by these changes includes the NTSC, PAL and JPN executables and will automatically pick the correct executable for the ROM present in the user data directory; if multiple ROMs are present it'll pick the first it finds in the order `ntsc-final`, `ntsc-1.0`, `jpn-final` and `pal-final` in order. Additionally a specific executable can be run by simply passing it as the first command line parameter to the `flatpak run` command, i.e. `flatpak run io.github.fgsfdsfgs.perfect_dark pd.jpn` will force running the Japanese executable.

Finally, any of the standard command-line arguments can also be passed in, by default they'll go to the automatically detected executable or with a specified executable as running that normally.

### CODE REVIEW

**Comment by peerchemist** [comment]
It works wonderfully. Thanks.

**Comment by fgsfdsfgs** [comment]
This is nice. Where did you get the icon from?

**Comment by fpiesche** [comment]
> This is nice. Where did you get the icon from?

The icon is sourced from https://www.steamgriddb.com/icon/9007.

**Comment by fpiesche** [comment]
For what it's worth, the Flatpak build could also be made independent of the workflows very easily by building the executables for the Flatpak as part of the manifest there - but as the workflows already build the Linux executables on Ubuntu the manifest instead just picks up the existing builds and installs them into a package.

The Flatpak Freedesktop runtime matches Ubuntu in terms of system library versions so this shouldn't cause any problems; however if we want to do things Properly I'd be happy to make the small modifications needed to run the Flatpak build entirely independently.

**Comment by fgsfdsfgs** [comment]
Merged. I will possibly replace the icon later, maybe with one of the suggestions in #238.

**Pull request merged**
