### PR TITLE
Multiple input updates

### PR DESCRIPTION
**Pull request by cylonicboom**
Summary of changes:
- maps Q to radial menu / menu accept
- maps E to menu cancel / use
- maps xbox Y/B to forward / back weapons
- maps xbox B to menu accept
- maps xbox A to menu cancel / use

We need separate menu-accept and menu-cancel use buttons because use is handled differently in the menus in N64/1964 vs Xbox.

Addresses these issues:

- #31 
- #40 
- #41

### CODE REVIEW

**Comment by cylonicboom** [comment]
I found an issue w/ this PR:

~~FIXED  mp forward / back is broken~~

moving to draft for now

**Comment by cylonicboom** [comment]
> I found an issue w/ this PR:
> 
> ~FIXED mp forward / back is broken~
> 
> moving to draft for now

Fixed up the controller binds & tested w/ camspy.

**Comment by cylonicboom** [comment]
~~FIXED: remote mine detonation~~

**Comment by cylonicboom** [comment]
Slayer controls feel okay with these button mappings.

**Comment by cylonicboom** [comment]
I found a regression w/ not being able to release grabbables unless you swing them around like mario64 and let go. moving to draft.

**Comment by LanHikariDS** [comment]
> maps xbox B to menu accept
> maps xbox A to menu cancel / use

Wait, what? Can 'Menu Cancel' and 'Use' not be split into distinct inputs?

**Comment by cylonicboom** [comment]
> > maps xbox B to menu accept
> > maps xbox A to menu cancel / use
> 
> Wait, what? Can 'Menu Cancel' and 'Use' not be split into distinct inputs?

in 1964 / N64: we expect the use button (e-keyboard or b-n64) to use and to cancel menus
in xbla we expect the use button to accept menus, and weapon back to go back in menus
when using a switch controller (especially if used to playing 1964 on the steam deck) you'd expect B to use / go back, and A to switch back / cancel menus (I realize now I need to implement this.)


I just realized when I was writing this that I should include a config option to treat the controller with xbla-style bindings or switch-style bindings.

Okay here's the things I need to fix:

~~- [ ] config option, per player, to treat as A/B buttons as switch vs xbla-style~~
~~- [ ] when using switch-style controller: treat weaponback as menuback~~
- [x] Readme updates detailing the changes, layouts, and rationale
- [x] Fix the grabbable issue, but take video first b/c it's kind of fun

**Comment by fgsfdsfgs** [comment]
I would say the XBLA/Switch option isn't really necessary if we're going to have rebindable buttons in the future. If you still think it is necessary, maybe hold off on that until there's an extended options menu or something, I feel like it'd be a bit awkward reading those flags for each individual player from the config.

**Comment by cylonicboom** [comment]
> I would say the XBLA/Switch option isn't really necessary if we're going to have rebindable buttons in the future. If you still think it is necessary, maybe hold off on that until there's an extended options menu or something, I feel like it'd be a bit awkward reading those flags for each individual player from the config.

Agreed. The ability to map use / accept / cancel separately would make that not needed directly.  Also, what's considered "A and B" for the purposes of mine detonation. For now I'll take out the abstraction layer that's only for switch / xbla handfeel and it can be handled more elegantly.

**Comment by LanHikariDS** [comment]
So the current default is for menus to go _against_ the standard layout for PC controllers?

**Pull request merged**
