### PR TITLE
port-net: Perfect Dark Plus Mod (Netplay) (WIP)

### PR DESCRIPTION
**Pull request by jonaeru**

### CODE REVIEW

**Comment by Knaxia** [comment]
I'm a bit curious about this. I've seen this pop a few times, I wanted to see, but apart from adding the options for the Skedar and Dr. Caroll, and adding the new levels in the list, the rest such as models and level data are missing of course.

I'm not too skilled into turning the existing mod to work with this, I guess you have to make a mod version of the PD+ mod, but out from extracting a few things from the patched rom, I don't really know to make this work correctly. I know it seems more like a personal test version, but still intrigued.

**Comment by jonaeru** [comment]
@Knaxia 
Sorry, I meant to create a PR in my project, but I made a mistake, so closed.
It works by using the Modding feature.
Please check the wiki I created.
https://github.com/jonaeru/perfect_dark/wiki/How-to-Play-Mods

**Comment by Knaxia** [comment]
Oh wow, this is everything I wanted and more!

I really enjoyed playing PD+ on my actual N64 (everdrive), but being able to also have the 2 other mods and play it on PC too, that's just amazing!

Thanks a bunch for your time on this, really appreciate it!

**Comment by jonaeru** [comment]
Thank you!

**Pull request closed without merging**
