### PR TITLE
Add an exit option to main menu

### PR DESCRIPTION
**Pull request by kronflux**
In Fullscreen there is currently no way to close the game without using Alt+F4. This adds an option "Exit" to the Main Menu, which asks to confirm before performing exit.

I did attempt to add a new item to the language JSON(something like "Are you sure you want to exit?", but doing so seems to crash the game when those new language items are used. I'm not certain if this is a memory limitation, a pre-defined number of language items, a range of items that are valid for the menu(going from 187 to 496 might be out of range?) or something entirely different.
There may also be a more graceful or already defined method of exiting I'm unaware of. This is just a quick and dirty option to present the idea for the PC port.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
The lang json files in the port are only used to generate some constants, the actual strings are loaded from the ROM. We will need a way to extend string tables sooner or later.

**Comment by kronflux** [comment]
Ahh that makes more sense. Thanks for the clarification. But yeah, for now "Exit" is already in the game, so it works well enough until then :)

**Comment by Graslu** [comment]
Just a small nitpick - Shouldn't the option default on "No" to be consistent with the rest in-game options such as abort mission or switch agent?

**Comment by fgsfdsfgs** [comment]
That can be done.

**Pull request merged**
