### PR TITLE
Add option to enable / disable pausing

### PR DESCRIPTION
**Pull request by cylonicboom**
- implements "Enable Pausing" option in `Extended -> Video". It takes effect immediately. 
- input-related gameplay checks use `g_Vars.currentplayer->pausemode` instead of `lvIsPaused()`
- input-related fixes when disabling pausing in solo
- allocate extra memory for `invmenu`, `gunmenu` just for inventory models

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
That seems to be a lot of changes just to disable pausing. Doesn't the game already support this in Combat Sim? Can that mechanism not be reused for other modes?

**Comment by cylonicboom** [comment]
I have some archived branches somewhere when I was experimenting with this idea on N64 decomp. 

Eventually I decided that untangling up the lifecycle stuff for the menubg blur, music, `g_lvPaused` vs `currentplayer->pausemode` and making it look-and feel like the rest of the solo mode felt better as a player and felt less scary than looking up all the "is mp running" checks just for a degraded menu.

Also allocating a memory for an extra "gunmem for inventory models" is needed to get menu models to work outside of training mode since gunmem (vanilla allocation for menu models) is shared w/ Jo's hands and her third-person body.

I haven't tested split-screen coop or combat sim w/ the port version yet. I'll do that today and update this thread.

**Comment by cylonicboom** [comment]
I found some issues with split screen. I'll submit a fixup.

**Comment by tunbridgep** [comment]
I have been trying this branch, it seems to work well.

Just a quick request: Could you make it so that mission music keeps playing instead of the Menu music if we're anywhere other than the default Institute map? Maybe as an option somewhere. Switching tracks whenever opening the menu seems a bit strange when the menu is working in real-time.

**Comment by cylonicboom** [comment]
> I have been trying this branch, it seems to work well.
> 
> 
> 
> Just a quick request: Could you make it so that mission music keeps playing instead of the Menu music if we're anywhere other than the default Institute map? Maybe as an option somewhere. Switching tracks whenever opening the menu seems a bit strange when the menu is working in real-time.

Fair enough. It might make sense to move the pause options to another submenu. I just put it in video because it was a bossy mutator.

**Comment by NeonNyan** [comment]
This crashes on lv startup on coop.

**Comment by cylonicboom** [comment]
> This crashes on lv startup on coop.

fixed: https://github.com/fgsfdsfgs/perfect_dark/pull/358/commits/7fe34f26dd91e6d2167cf47cd26121da2de1bad9

**Comment by cylonicboom** [comment]
As discussed this should be a mod given the extend of changes.

**Pull request closed without merging**
