### PR TITLE
Fixed flipped texts and menu elements that were beyond the near clip plane

### PR DESCRIPTION
**Pull request by MaikelChan**
Since OpenGL 2.1 is used, I opted to use the `GLAD_GL_ARB_depth_clamp` extension and check if it's available before enabling depth clamp, so the game should maintain the same compatibility.

### CODE REVIEW

**Comment by ghost** [comment]
This also fixes the camera clipping thru geometry, but the viewmodels still clip through the walls.
Before:
before
After:
after

**Comment by fgsfdsfgs** [comment]
That's interesting, I can't get the guns to clip through the world on my end. Where does that happen?

**Comment by ghost** [comment]
It occurs inside the caves in Villa.

**Comment by fgsfdsfgs** [comment]
Must be a problem with how I handle `gSPPerspNormalize` then.

**Pull request merged**
