### PR TITLE
Remove most of the busywaiting

### PR DESCRIPTION
**Pull request by iamgreaser**
DO NOT MERGE AS-IS - this is to be considered 32-bit x86 Linux-specific due to me struggling to make the headers behave properly and also needing an API exposed.

pd.exe tends to go down to about 9% of a CPU core in the main menu on My Machine(tm) at the default screen resolution.

The original version of this patch was something I put together on 2023-09-12 but didn't get around to polishing it up. It shouldn't be difficult to patch this further to make it work on Windows, but I'd like to see something with notably less layer pollution.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
Did you try the FPS limiter (`FramerateLimit` in `pd.ini`) or just turning VSync on? There's already a sleep call in the former and the latter should sleep by definition. There should be no need for any extra sleep calls.

**Comment by iamgreaser** [comment]
`FramerateLimit` was already set to `60`, and I get about 80% of a core in the main menu. With `FramerateLimit=0` it uses 100% of a core.
`VSync=1` seems to have no effect although I do have vsync forced via `.drirc`.

**Comment by fgsfdsfgs** [comment]
In any case, I'd really rather not change that game loop. Either the sleeping is broken on Linux in `gfx_sdl2.cpp` or the problem is somehow on your end. I'd advise looking into the former before you go changing the N64 code.
The frame timing code is something that I've been screwing with for years and I still can't get it good. You might end up fixing your situation, but in the process break it on someone else's machine.

**Comment by iamgreaser** [comment]
OK, I've looked a bit further using `gprof` (build using GCC with the `-pg` flag) and there are two places I can see where busywaiting happens:

- `port/src/pdmain.c`, function `mainLoop()`, exactly where I've patched it.
- `src/game/timing.c`, function `frametimeCalculate()`, in the do/while loop.

If one does a `usleep(100)` before each call to `osGetCount()` in those specific cases, then the CPU usage drops down to about 8% of a core in the main menu, and the remaining bottlenecks are mostly evenly-distributed and pertain to actually doing things (e.g. drawing triangles).

The "proper" solution would be to provide an API to make it sleep (maybe `osSleepUntilCount()`?) and place one of those immediately before each of the two `osGetCount()` calls, providing an appropriate argument to the function of course.

----

A bit more info about the figures:

I said "My Machine(tm)" because my setup is a bit weird: It's a 7950X3D 16-core / 32-thread CPU, but I'm using DRI PRIME for the GPU as the stupid BIOS loves to forget to turn the output ports on for the dedicated GPU.

So I'm using the integrated GPU to drive the display, while the game uses the dedicated GPU for rendering which is a 7900 XTX -- the integrated GPU lags in menus at 3840x2160 hence why I use the dedicated GPU.

**Comment by iamgreaser** [comment]
...ah crap I missed one thing:

Commenting out the `left -= 15000UL;` line in `port/fast3d/gfx_sdl2.cpp`'s `sync_framerate_with_timer()` is also necessary to get the CPU usage down if this approach is taken, otherwise it ends up at about 18% of a core in menus. Yes, this defeats the purpose of the logic that's there.

**Comment by fgsfdsfgs** [comment]
The reason that logic is there in the first place is to provide a more accurate framerate cap. If you do it like normal (i.e. just sleep the remaining time away every frame), it ends up being janky and unstable on most systems, especially if vsync is enabled at the same time.
It might be a good idea to provide an option for a different approach if CPU time concerns the user, but for example on my machine (on Windows) CPU usage usually hovers around 2-3% with a 60FPS frame cap and around 8-9% with a 144FPS cap, so I never really saw the need to fix it. Then again, the Windows code uses waitable timers, so maybe `nanosleep` is not exactly a good replacement.
Might also be a good idea to make the `DO_YIELD()` macro public and put one in `mainLoop`.

**Comment by iamgreaser** [comment]
How many cores/threads do you have? On Linux, "100% CPU usage" means 100% of a single core (or hardware thread), whereas on Windows, it means all cores are being used.

**Comment by fgsfdsfgs** [comment]
Ryzen 7 5700X, should be 8 / 16.

**Comment by iamgreaser** [comment]
OK, so that would translate to roughly 50% of a core for a 60 FPS cap, and roughly 100% of a core for a 144 FPS cap. (EDIT: By "core" I mean hardware thread.)

**Comment by iamgreaser** [comment]
UPDATE: Turns out some of the more elaborate stuff I tried actually results in co-op mode lagging quite badly. Also, merely having a controller plugged in seems to lower the CPU usage. However, setting vibration to 0 for that controller and then restarting the game makes it use as much CPU as it usually does.

**Commenting out the `left -= 15000UL;` and doing a `usleep(100);` at the start of each of the two hotspots performs OK and removes almost all of the busywaiting.**

Under those conditions, co-op uses about 50% of a CPU core at the start of Carrington Villa PA. This is with the default optimisation level of `-Og`.
I'll leave this one to ferment for now, I have a basic case that Works For Me(tm) and it's probably better if I start looking into stuff like performance slowdowns and netplay desyncs.

**Comment by fgsfdsfgs** [comment]
Looks like you're right, I see intermittent spikes to ~100% on several cores when the game is running.
I'll see if I can simplify the whole framerate limiter system a little bit and include an option for sleep calls in those places. Having two different settings for framerate is insane enough already.

What performance slowdowns are you talking about?

**Comment by iamgreaser** [comment]
If I try to make it sleep until the end of each of those hotspots, it drops down to about 15 FPS at the start of Villa PA Co-op. The simpler "wait 100 usecs each iteration" approach does not cause this to happen.

**Comment by fgsfdsfgs** [comment]
@iamgreaser 
Added an option for the extra sleeps, called `Game.ExtraSleep`, which does pretty much what was described in the past few comments. Check that out and see if it's good enough to solve your problem.

**Comment by iamgreaser** [comment]
It works well, even for Villa PA Co-op. Thank you for sorting something out.

I'll close this issue.

**Pull request closed without merging**
